// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA24_PRN221_3W_G3_KoiCareSystemAtHome.Repositories.Models;

public partial class Order
{
    public long Id { get; set; }

    public DateTime OrderDate { get; set; }

    public long Quantity { get; set; }

    public decimal TotalPrice { get; set; }

    public long UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Priority { get; set; }

    public string OrderNotes { get; set; }

    public string CouponCode { get; set; }

    public string Status { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}