// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA24_PRN221_3W_G3_KoiCareSystemAtHome.Repositories.Models;

public partial class Payment
{
    public long Id { get; set; }

    public long OrderId { get; set; }

    public decimal Total { get; set; }

    public DateTime PaymentDate { get; set; }

    public string Notes { get; set; }

    public long PayerId { get; set; }

    public long PaymentMethodId { get; set; }

    public bool Status { get; set; }

    public decimal DiscountApplied { get; set; }

    public decimal TaxAmount { get; set; }

    public virtual Order Order { get; set; }

    public virtual User Payer { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}