// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FA24_PRN221_3W_G3_KoiCareSystemAtHome.Repositories.Models;

public partial class WaterParameter
{
    public long Id { get; set; }

    public long? PondId { get; set; }

    public long? MeasurementDate { get; set; }

    public decimal? Temperature { get; set; }

    public decimal? Salinity { get; set; }

    public decimal? Ph { get; set; }

    public decimal? O2 { get; set; }

    public decimal? No2 { get; set; }

    public decimal? No3 { get; set; }

    public decimal? Po4 { get; set; }

    public virtual Pond Pond { get; set; }
}